export const DATASET_ID_CHANGE = "DATASET_ID_CHANGE";
export type DATASET_ID_CHANGE = typeof DATASET_ID_CHANGE;

export const INIT_DATASET_LIST = "INIT_DATASET_LIST";
export type INIT_DATASET_LIST = typeof INIT_DATASET_LIST;

export const EWEIGHT_CHANGE = "EWEIGHT_CHANGE";
export type EWEIGHT_CHANGE = typeof EWEIGHT_CHANGE;

export const NLABEL_CHANGE = "NLABEL_CHANGE";
export type NLABEL_CHANGE = typeof NLABEL_CHANGE;

export const SELECTED_NODE_ID_LIST_CHANGE = "SELECTED_NODE_ID_LIST_CHANGE";
export type SELECTED_NODE_ID_LIST_CHANGE = typeof SELECTED_NODE_ID_LIST_CHANGE;

export const SHOW_SOURCE_CHANGE = "SHOW_SOURCE_CHANGE";
export type SHOW_SOURCE_CHANGE = typeof SHOW_SOURCE_CHANGE;

export const SPECIFIC_NODE_ID_LIST_CHANGE = "SPECIFIC_NODE_ID_LIST_CHANGE";
export type SPECIFIC_NODE_ID_LIST_CHANGE = typeof SPECIFIC_NODE_ID_LIST_CHANGE;


export const SELECT_INSPECT_NODE_CHANGE = "SELECT_INSPECT_NODE_CHANGE";
export type SELECT_INSPECT_NODE_CHANGE = typeof SELECT_INSPECT_NODE_CHANGE;

export const PREV_GRAPH_JSON_CHANGE = "PREV_GRAPH_JSON_CHANGE";
export type PREV_GRAPH_JSON_CHANGE = typeof PREV_GRAPH_JSON_CHANGE;


export const CLEAR_ID_INFO = "CLEAR_ID_INFO";
export type CLEAR_ID_INFO = typeof CLEAR_ID_INFO;

export const EXTENDED_MODE_CHANGE = "EXTENDED_MODE_CHANGE";
export type EXTENDED_MODE_CHANGE = typeof EXTENDED_MODE_CHANGE;

export const GRAPHVIEWSETTINGMODAL_VISIBLE_CHANGE = "GRAPHVIEWSETTINGMODAL_VISIBLE_CHANGE";
export type GRAPHVIEWSETTINGMODAL_VISIBLE_CHANGE = typeof GRAPHVIEWSETTINGMODAL_VISIBLE_CHANGE;

export const GRAPHVIEWSTATE_CHANGE = "GRAPHVIEWSTATE_CHANGE";
export type GRAPHVIEWSTATE_CHANGE = typeof GRAPHVIEWSTATE_CHANGE;

export const ENABLE_FORCE_DIRECTED_CHANGE = "ENABLE_FORCE_DIRECTED_CHANGE";
export type ENABLE_FORCE_DIRECTED_CHANGE = typeof ENABLE_FORCE_DIRECTED_CHANGE;


/*// 定义增加 state 类型常量
export const INCREMENT = "INCREMENT";
export type INCREMENT = typeof INCREMENT;

// 定义减少 state 类型常量
export const DECREMENT = "DECREMENT";
export type DECREMENT = typeof DECREMENT;
*/